<?php

function user_greetings_menu() {
    $items = array();
    $items['welcome'] = array(
            'title' => "Welcome",
            'page callback' = 'say_welcome',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
    $items['farewell'] = array(
            'title' => "Farewell",
            'page callback' => 'say_farewell',
            'access_callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function say_welcome() {

}
